name: Sphinx Documentation
description: GitHub Action to compile and publish sphinx documentation
author: itsmycargo

inputs:
  sphinx_builder:
    description:
    required: false
    default: html
  sourcedir:
    description:
    required: false
    default: .
  sphinx_build_args:
    description:
    required: false
  confluence_server:
    description:
    required: false
  confluence_user:
    description:
    required: false
  confluence_pass:
    description:
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SPHINX_BUILDER: ${{ inputs.sphinx_builder }}
    SOURCEDIR: ${{ inputs.sourcedir }}
    SPHINX_BUILD_ARGS: ${{ inputs.sphinx_build_args }}
    CONFLUENCE_SERVER: ${{ inputs.confluence_server }}
    CONFLUENCE_USER: ${{ inputs.confluence_user }}
    CONFLUENCE_PASS: ${{ inputs.confluence_pass }}
