name: Sphinx Documentation
description: GitHub Action to compile and publish sphinx documentation
author: itsmycargo

inputs:
  base:
    description: Base OpenAPI specification
    required: true
  revision:
    description: Revised OpenAPI specification
    required: true
  github-token:
    description: GitHub Token as provided by secrets
    default: ${{ github.token }}
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SPHINX_BUILDER: ${{ inputs.sphinx_builder }}
    SOURCEDIR: ${{ inputs.sourcedir }}
    SPHINX_BUILD_ARGS: ${{ inputs.sphinx_build_args }}
    CONFLUENCE_SERVER: ${{ inputs.confluence_server }}
    CONFLUENCE_USER: ${{ inputs.confluence_user }}
    CONFLUENCE_PASS: ${{ inputs.confluence_pass }}
